; StackTabs - Dracula theme

[Theme]
Preset=custom
Background=282a36
TabBarBg=21222c
TabActiveBg=bd93f9
TabActiveText=f8f8f2
TabInactiveBg=343746
TabInactiveBgHover=44475a
TabInactiveText=f8f8f2
IconColor=6272a4
ContentBorder=44475a
WindowText=f8f8f2
FontName=Segoe UI
FontNameTab=Segoe UI Semibold
FontSize=9
FontSizeClose=10
IconFontSize=16
